config/routes.rb
Rails.application.routes.draw do
  root             'static_pages#home'
  get 'find'    => 'reports#index'
  get 'form'    => 'reports#new'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'signup'  => 'users#new'
  get 'show'    => 'users#show'
  get 'edit'    => 'users#edit'
  get 'users'   => 'users#index'

  delete 'favorite' => 'favorites#destroy'
  post 'defavorite' => 'favorites#create'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :users do
    get :favorites, on: :member
  end
  resources :reports, only: [:create, :destroy, :index, :show]
  resources :reports do
    resource :favorites, only: [:create, :destroy]
  end

  resources :destinations
  resources :areas, only: [] do
    resources :countries
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @q = Report.search(params[:q])
    if @q != nil
      @reports = @q.result(distinct: true).paginate(page: params[:page], per_page: 10)
    else
      @reports = Report.paginate(page: params[:page], per_page: 10)
    end
  end

  def help
  end

  def about
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
  </head>
  <body>
    <h1>About</h1>
    <p>
      The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
      Tutorial</em></a> is a
      <a href="http://railstutorial.jp">book</a> and
      <a href="http://screencasts.railstutorial.org/">screencast series</a>
      to teach web development with
      <a href="http://rubyonrails.org/">Ruby on Rails</a>.
      This is the sample application for the tutorial.
    </p>
  </body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<div class="center">
    <h1>What is Trapedia?</h1>
    <p>
      Trapediaは海外旅行を考えている人向けの情報収集プラットフォームです．</br>
      海外旅行のプランを立てる際，言語の違いからくる不安や安全面等の海外旅行特有の条件があると思います．</br>
      旅行に行かれた方はその経験を<%= link_to "投稿", form_path %>し情報をシェア，これから旅行に行かれる方は投稿された経験を<%= link_to "検索", find_path %>しより良い旅行プランを立てましょう．</br>
    </p>
</div>

app/views/static_pages/home.html.erb
<div class="sqere_background", style="background-image:url(<%= asset_path "Antelope7.jpg" %>)" data-stellar-background-ratio="0.5"/>
  <div class="center">
    <h1>Welcome to the Trapedia</h1>
    <h2>
      if this is the first time of visiting this page for you, check the <%= link_to "HELP", help_path %> page.
    </h2>
    <h2>
      Do you wanna <%= link_to "FIND", find_path %> the reports with various condition?</br>
      Do you wanna <%= link_to "POST", form_path %> your memoirs?</br>
      Do you wanna <%= link_to "SIGN UP", new_user_path %>?</br>
    </h2>
  </div>
</div>