config/routes.rb
Rails.application.routes.draw do
  root             'static_pages#home'
  get 'find'    => 'reports#index'
  get 'form'    => 'reports#new'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'signup'  => 'users#new'
  get 'show'    => 'users#show'
  get 'edit'    => 'users#edit'
  get 'users'   => 'users#index'

  delete 'favorite' => 'favorites#destroy'
  post 'defavorite' => 'favorites#create'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :users do
    get :favorites, on: :member
  end
  resources :reports, only: [:create, :destroy, :index, :show]
  resources :reports do
    resource :favorites, only: [:create, :destroy]
  end

  resources :destinations
  resources :areas, only: [] do
    resources :countries
  end

end

app/models/report.rb
class Report < ActiveRecord::Base
  has_many :sub_categories, ->{ order(:id) }
  has_many :favorites, dependent: :destroy
  belongs_to :user

  default_scope -> {order(created_at: :desc)}
  validates :user_id, presence: true
  validates :title, presence: true, length: {maximum: 30}
  validates :cost, presence: true, length: {maximum: 30}
  validates :safety, presence: true, length: {maximum: 30}
  validates :abroadArea, presence: true, length: {maximum: 30}
  validates :abroadCountry, presence: true, length: {maximum: 30}
  validates :purpose, presence: true, length: {maximum: 30}
  validates :content, presence: true

  mount_uploader :image, ImageUploader


  def favorited_by? user
    favorites.where(user_id: user.id).exists?
  end

end

app/controllers/reports_controller.rb
require 'net/http'

class ReportsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  helper_method :sort_column, :sort_direction


  def create
    @destination = Destination.new
    @report = current_user.reports.build(report_params)
    if @report.save
      flash[:success] = "Report created!"
      redirect_to current_user
    else
      render 'new'
    end
  end

  def index
    @destination = Destination.new
    @q = Report.search(params[:q])
    if @q != nil
      @reports = @q.result(distinct: true).paginate(page: params[:page], per_page: 10)
    else
      @reports = Report.paginate(page: params[:page], per_page: 10)
    end
  end

  def show
    @report = Report.find(params[:id])
  end

  def edit
    @destination = Destination.new
    @report = Report.find(params[:id])
  end

  def new
     if logged_in?
       @destination = Destination.new
       @report = current_user.reports.build
     else
       logged_in_user
     end
  end

  def update
    @destination = Destination.new
    @report = Report.find(params[:id])
    if @report.update_attributes(report_params)
      flash[:success] = "Report updated"
      redirect_to @report
    else
      render 'edit'
    end
  end

  def destroy
    Report.find(params[:id]).destroy
    flash[:success] = "Report deleted"
    redirect_to current_user
  end

  def report_params
    params.require(:report).permit(:title, :cost, :safety, :abroadArea, :abroadCountry, :purpose, :content, :image)
  end


  private
  def destination_params
    params.require(:destination).permit(:name, :category_id, :sub_category_id)
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end

  def sort_column
    Report.column_names.include?(params[:sort]) ? params[:sort] : "cost"
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
  
end

app/views/reports/_form.html.erb
  <%= form_for(@report) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <aside class="col-md-6 col-md-offset-3 col-xs-6 col-xs-offset-3 col-sm-6 col-sm-offset-3" style="background-color: #ffffff;">
      <div class="center">
        <h1><%= yield(:h1)%></h1>
      </div>
    <%= f.label "タイトル"%>
    <%= f.text_field :title, :placeholder => "30文字以内", :class => "title_field"%>

  <br/>
    <div class="col-md-6 col-xs-6 col-sm-6"style="background-color: #ffffff;">
      <dt><%= f.label "地域" %></dt>
      <% area_options = Area.order(:id).map { |c| [c.name, data: { children_path: area_countries_path(c) }] } %>
      <dd><%= f.select :abroadArea, area_options, { include_blank: true }, class: 'select-parent' %></dd>
      <br/>
      <dt><%= f.label "国" %></dt>
      <% countries = @destination.area.try(:countries) || [] %>
      <% country_options = countries.map { |c| [c.name] } %>
      <dd><%= f.select :abroadCountry, country_options, { include_blank: true }, class: 'select-children'%></dd>
      <br/>
      <dt><%= f.label "目的" %></dt>
      <dd><%= f.select :purpose , options_for_select(["観光", "ショッピング", "世界遺産", "自然"]), :include_blank => true %></dd>
      <br/>
    </div>
    <div class="col-md-6 col-xs-6 col-sm-6 "style="background-color: #ffffff;">
      <dt><%= f.label "費用" %></dt>
      <dd><%= f.text_field :cost, :class => "cost_field" %></dd>
      <br/>
      <dt><%= f.label "安全度" %></dt>
      <dd><%= f.text_field :safety, :class => "safety_field" %></dd>
    </div>
  </aside>
  <aside class="col-md-6 col-md-offset-3 col-xs-6 col-xs-offset-3 col-sm-6 col-sm-offset-3" style="background-color: #ffffff;">
    <%= f.label "文章" %></br>
    <%= f.text_area :content, size: "90x10" %>
    <br/>
    <%=f.label :image,"ユーザー画像" %>
    <%= f.file_field :image %>
    <br/>
    <div class="center">
    <%= f.submit yield(:button_text) %>
  </div>
  </aside>
    <% end %>

app/views/reports/_report.html.erb
<li id="report-<%= report.id %>">
  <span class="title"><%= link_to report.title, report %></span>
  ☆<%= report.favorites.count %>
  <span class="timestamp">Posted <%= time_ago_in_words(report.created_at) %> ago.</span>
  <% if report.user.id == current_user.id %>
    <%= link_to "体験談を編集", edit_report_path(report.id) %>
    <%= link_to "体験談を削除", report, method: :delete, data: {confirm: "Are you sure?"} %>
  <% end %>
</li>

app/views/reports/_searcher.html.erb
<div class="center">
  <h1>体験記検索</h1>
  <!-- <%= @destination.name %> -->
</div>

<%= search_form_for @q do |f| %>
  <aside class="col-md-6 col-md-offset-3"style="background-color: #eaeaea;">
    <div class="col-md-6">
      <dt><%= f.label :abroadArea, "地域" %></dt>
      <% area_options = Area.order(:id).map { |c| [c.name, data: { children_path: area_countries_path(c) }] } %>
      <dd><%= f.select :abroadArea_eq, area_options, { include_blank: true }, class: 'select-parent', remote: true %></dd>
      </br>
      <dt><%= f.label :abroadCountry, "国" %></dt>

      <% countries = @destination.area.try(:countries) || [] %>
      <% country_options = countries.map { |c| [c.name] } %>
      <dd><%= f.select :abroadCountry_eq, country_options, { include_blank: true }, class: 'select-children', remote: true%></dd>

      </br>
      <dt><%= f.label :purpose, "目的" %></dt>
      <dd><%= f.select :purpose_eq, options_for_select(["観光", "ショッピング", "世界遺産", "自然"]), :include_blank => true, :class => "select" %></dd>
      </div>
    <div class="col-md-6">
      <dt><%= f.label :cost, "費用" %></dt>
      <dd><%= f.search_field :cost_gteq, :class => "cost_field" %> ~  <%= f.search_field :cost_lteq, :class => "cost_field" %> 万円</dd>
      </br>
      <dt><%= f.label :safety, "安全度" %></dt>
      <dd><%= f.search_field :safety_gteq, :class => "safety_field" %> ~  <%= f.search_field :safety_lteq, :class => "safety_field" %></dd>
      </br></br></br>
      <%= f.submit "検索", :class => "submit" %>
    </div>
  </aside>
<% end %>

app/views/reports/_tableDisplay.html.erb
<div class="col-md-6 col-md-offset-3" style="background-color: #ffffff;">
  <%= will_paginate %>
  <table class="table table-bordered table-striped" >
    <thead>
      <tr>
        <th>タイトル</th>
        <th>費用</th>
        <th>安全度</th>
        <th>地域</th>
        <th>国</th>
        <th>目的</th>
        <th>お気に入り数</th>
      </tr>
    </thead>

    <tbody>
      <% @reports.each do |report| %>
          <tr>
            <td><%= link_to report.title, report %></td>
            <td><%= report.cost %></td>
            <td><%= report.safety %></td>
            <td><%= report.abroadArea %></td>
            <td><%= report.abroadCountry %></td>
            <td><%= report.purpose %></td>
            <td><%= report.favorites.count %></td>
          </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate %>
</div>

app/views/reports/edit.html.erb
<% provide(:title, "report user") %>
<% provide(:button_text, "更新") %>
<% provide(:h1, "体験記更新") %>
<div class="center">
</div>
  <%= render 'form' %>

app/views/reports/index.html.erb
<% provide(:title, "Find") %>
<div align="center">
  <%= render 'searcher' %>
  <%= render 'tableDisplay' %>
</div>

app/views/reports/new.html.erb
<% provide(:title, "Post") %>
<% provide(:button_text, "作成") %>
<% provide(:h1, "体験記作成") %>
<%= render 'form' %>

app/views/reports/show.html.erb
<div class="repo">
<h1><%= @report.title %>
  <% if logged_in? %>
    <div id="re">
    <% if @report.favorited_by? current_user %>
      <%= link_to "★", report_favorites_path(@report), method: :delete, remote: true%>
    <% else %>
      <%= link_to "☆", report_favorites_path(@report), method: :post, remote: true %>
    <% end %>
    <%= @report.favorites.count %>
    </div>
  <% else %>
    <% store_location %>
    <%= link_to "☆", report_favorites_path(@report), method: :post %>
    <%= @report.favorites.count %>
  <% end %>
</h1>

<aside class="col-md-6 col-md-offset-3">
<h2>
<li>費用：<%= @report.cost %></li></br>
<li>安全度：<%= @report.safety %></li></br>
<li>地域：<%= @report.abroadArea %></li></br>
<li>国：<%= @report.abroadCountry %></li></br>
<li>目的：<%= @report.purpose %></li></br>
<li>内容：<%= @report.content %></li>
</h2>
<% if @report.image? %>
  <%= image_tag @report.image.url %>
<% end %>
</aside>

<!-- <aside class="col-md-2 col-md-offset-10"> -->

<!-- </aside> -->
</div>