config/routes.rb
Rails.application.routes.draw do
  root             'static_pages#home'
  get 'find'    => 'reports#index'
  get 'form'    => 'reports#new'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'signup'  => 'users#new'
  get 'show'    => 'users#show'
  get 'edit'    => 'users#edit'
  get 'users'   => 'users#index'

  delete 'favorite' => 'favorites#destroy'
  post 'defavorite' => 'favorites#create'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :users do
    get :favorites, on: :member
  end
  resources :reports, only: [:create, :destroy, :index, :show]
  resources :reports do
    resource :favorites, only: [:create, :destroy]
  end

  resources :destinations
  resources :areas, only: [] do
    resources :countries
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "Trapedia", root_path %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Trapedia", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Help",    help_path %></li>
        <li><%= link_to "Post",    form_path %></li>
        <li><%= link_to "Find",    find_path %></li>
        <li><%= link_to "All users", users_path  %></li>
        <% if logged_in? %>
          <li class ="dropdown" >
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login",   login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
  </body>
</html>